/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import javax.swing.JOptionPane;


/**
 *
 * @author DAY
 */
public class JFrameTemperatura extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTemperatura
     */
    public JFrameTemperatura() {
        initComponents();
        buttonGroup1.add(jRadioButtonFahrenheit);
        buttonGroup1.add(jRadioButtonCelsius);
        buttonGroup1.add(jRadioButtonKelvin);
        buttonGroup1.add(jRadioButtonRadianes);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonConvertir = new javax.swing.JButton();
        jTextFieldIngresarNumeros = new javax.swing.JTextField();
        jRadioButtonFahrenheit = new javax.swing.JRadioButton();
        jRadioButtonCelsius = new javax.swing.JRadioButton();
        jRadioButtonKelvin = new javax.swing.JRadioButton();
        jRadioButtonRadianes = new javax.swing.JRadioButton();
        jLabelCoversorTemperatura = new javax.swing.JLabel();
        jLabelIngresarTempGrados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonConvertir.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jButtonConvertir.setText("Convertir");
        jButtonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertirActionPerformed(evt);
            }
        });

        jTextFieldIngresarNumeros.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextFieldIngresarNumeros.setText("9");
        jTextFieldIngresarNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIngresarNumerosActionPerformed(evt);
            }
        });

        jRadioButtonFahrenheit.setText("A Fahrenheit");

        jRadioButtonCelsius.setText("A Celsius");
        jRadioButtonCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCelsiusActionPerformed(evt);
            }
        });

        jRadioButtonKelvin.setText("A Kelvin");

        jRadioButtonRadianes.setText("A Radianes");
        jRadioButtonRadianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRadianesActionPerformed(evt);
            }
        });

        jLabelCoversorTemperatura.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelCoversorTemperatura.setText("Conversor de Temperatura");

        jLabelIngresarTempGrados.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelIngresarTempGrados.setText("Ingrese temperatura en Grados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButtonConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCoversorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIngresarTempGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonKelvin)
                    .addComponent(jRadioButtonFahrenheit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonRadianes)
                    .addComponent(jRadioButtonCelsius))
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldIngresarNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelCoversorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelIngresarTempGrados)
                .addGap(35, 35, 35)
                .addComponent(jTextFieldIngresarNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCelsius)
                    .addComponent(jRadioButtonFahrenheit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonKelvin)
                    .addComponent(jRadioButtonRadianes))
                .addGap(26, 26, 26)
                .addComponent(jButtonConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertirActionPerformed
        // TODO add your handling code here:
        try{
            Double temperatura = Double.parseDouble(jTextFieldIngresarNumeros.getText());
            String resultado;
            if(jRadioButtonFahrenheit.isSelected()){
                double fahrenheit = (temperatura * 9 / 5) + 32;
                resultado = "La temperatura en Fahrenheit es: " +fahrenheit+ "ºF";
                JOptionPane.showMessageDialog(this, resultado, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } else if(jRadioButtonCelsius.isSelected()){
                double celcius = (temperatura - 32) * 5 / 9;
                resultado = "La temperatura de Celcius es: " +celcius+ "ºC";
                 JOptionPane.showMessageDialog(this, resultado, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } else if(jRadioButtonKelvin.isSelected()){
                double kelvin = temperatura + 273.15;
                resultado = "La temperatura de Kelvin es: " +kelvin+ "ºK";
                 JOptionPane.showMessageDialog(this, resultado, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } else{
                resultado = "Por favor seleccione una opcion de conversion";
                 JOptionPane.showMessageDialog(this, resultado, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Por favor ingrese un numero valido.", "ERROR!!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonConvertirActionPerformed

    private void jTextFieldIngresarNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIngresarNumerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIngresarNumerosActionPerformed

    private void jRadioButtonCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCelsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCelsiusActionPerformed

    private void jRadioButtonRadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRadianesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRadianesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTemperatura().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonConvertir;
    private javax.swing.JLabel jLabelCoversorTemperatura;
    private javax.swing.JLabel jLabelIngresarTempGrados;
    private javax.swing.JRadioButton jRadioButtonCelsius;
    private javax.swing.JRadioButton jRadioButtonFahrenheit;
    private javax.swing.JRadioButton jRadioButtonKelvin;
    private javax.swing.JRadioButton jRadioButtonRadianes;
    private javax.swing.JTextField jTextFieldIngresarNumeros;
    // End of variables declaration//GEN-END:variables
}
