/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author Valentin Barros
 */
public class Credenciales extends javax.swing.JFrame {

    /**
     * Creates new form Credenciales
     */
    public Credenciales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPInicioDeCredenciales = new javax.swing.JDesktopPane();
        jPInicio = new javax.swing.JPanel();
        jLInicio = new javax.swing.JLabel();
        jPanelBotonesContraseña = new javax.swing.JPanel();
        jBOcultar = new javax.swing.JButton();
        jBVer = new javax.swing.JButton();
        jPIngreseLasCredenciales = new javax.swing.JPanel();
        jLUsuario = new javax.swing.JLabel();
        jLContraseña = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        jPFContraseña = new javax.swing.JPasswordField();
        jBVerificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Credenciales");

        jLInicio.setBackground(new java.awt.Color(204, 204, 204));
        jLInicio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLInicio.setText("Inicio de sesion");

        javax.swing.GroupLayout jPInicioLayout = new javax.swing.GroupLayout(jPInicio);
        jPInicio.setLayout(jPInicioLayout);
        jPInicioLayout.setHorizontalGroup(
            jPInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPInicioLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPInicioLayout.setVerticalGroup(
            jPInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jBOcultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ojos-cruzados.png"))); // NOI18N
        jBOcultar.setText("Ocultar");
        jBOcultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOcultarActionPerformed(evt);
            }
        });

        jBVer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ojo.png"))); // NOI18N
        jBVer.setText("Ver");
        jBVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesContraseñaLayout = new javax.swing.GroupLayout(jPanelBotonesContraseña);
        jPanelBotonesContraseña.setLayout(jPanelBotonesContraseñaLayout);
        jPanelBotonesContraseñaLayout.setHorizontalGroup(
            jPanelBotonesContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesContraseñaLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jBOcultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBVer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jPanelBotonesContraseñaLayout.setVerticalGroup(
            jPanelBotonesContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBOcultar, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jBVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPIngreseLasCredenciales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese las credenciales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLUsuario.setText("Usuario");

        jLContraseña.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLContraseña.setText("Contraseña");

        jTFUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTFUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFUsuarioActionPerformed(evt);
            }
        });

        jPFContraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jBVerificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/monitor.png"))); // NOI18N
        jBVerificar.setText("  Verificar");
        jBVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPIngreseLasCredencialesLayout = new javax.swing.GroupLayout(jPIngreseLasCredenciales);
        jPIngreseLasCredenciales.setLayout(jPIngreseLasCredencialesLayout);
        jPIngreseLasCredencialesLayout.setHorizontalGroup(
            jPIngreseLasCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPIngreseLasCredencialesLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPIngreseLasCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPIngreseLasCredencialesLayout.createSequentialGroup()
                        .addComponent(jLUsuario)
                        .addGap(54, 54, 54)
                        .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPIngreseLasCredencialesLayout.createSequentialGroup()
                        .addComponent(jLContraseña)
                        .addGap(18, 18, 18)
                        .addComponent(jPFContraseña)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPIngreseLasCredencialesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBVerificar)
                .addGap(141, 141, 141))
        );
        jPIngreseLasCredencialesLayout.setVerticalGroup(
            jPIngreseLasCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPIngreseLasCredencialesLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPIngreseLasCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUsuario)
                    .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPIngreseLasCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLContraseña)
                    .addComponent(jPFContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jBVerificar)
                .addGap(21, 21, 21))
        );

        jDPInicioDeCredenciales.setLayer(jPInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPInicioDeCredenciales.setLayer(jPanelBotonesContraseña, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDPInicioDeCredenciales.setLayer(jPIngreseLasCredenciales, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDPInicioDeCredencialesLayout = new javax.swing.GroupLayout(jDPInicioDeCredenciales);
        jDPInicioDeCredenciales.setLayout(jDPInicioDeCredencialesLayout);
        jDPInicioDeCredencialesLayout.setHorizontalGroup(
            jDPInicioDeCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBotonesContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDPInicioDeCredencialesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jDPInicioDeCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPIngreseLasCredenciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jDPInicioDeCredencialesLayout.setVerticalGroup(
            jDPInicioDeCredencialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPInicioDeCredencialesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPIngreseLasCredenciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jPanelBotonesContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPInicioDeCredenciales)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPInicioDeCredenciales)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBOcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOcultarActionPerformed
        // TODO add your handling code here:
        jPFContraseña.setEchoChar('*');
    }//GEN-LAST:event_jBOcultarActionPerformed

    private void jBVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerActionPerformed
        // TODO add your handling code here:
        jPFContraseña.setEchoChar((char)0);
    }//GEN-LAST:event_jBVerActionPerformed

    private void jTFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUsuarioActionPerformed

    private void jBVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerificarActionPerformed
        // TODO add your handling code here:
        String usuario = jTFUsuario.getText();
        String password = jPFContraseña.getText();
        if (usuario.equalsIgnoreCase("alumno@ulp.edu.ar") && password.equalsIgnoreCase("12345678")) {
            JOptionPane.showMessageDialog(this, "Bienvenido ");
        } else {
            JOptionPane.showMessageDialog(this, "Usuario y contraseña incorrectos ");
        }

    }//GEN-LAST:event_jBVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credenciales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credenciales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBOcultar;
    private javax.swing.JButton jBVer;
    private javax.swing.JButton jBVerificar;
    private javax.swing.JDesktopPane jDPInicioDeCredenciales;
    private javax.swing.JLabel jLContraseña;
    private javax.swing.JLabel jLInicio;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JPasswordField jPFContraseña;
    private javax.swing.JPanel jPIngreseLasCredenciales;
    private javax.swing.JPanel jPInicio;
    private javax.swing.JPanel jPanelBotonesContraseña;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
